// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DisconnectDTO.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_DisconnectDTO_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_DisconnectDTO_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "DTO.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_DisconnectDTO_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_DisconnectDTO_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_DisconnectDTO_2eproto;
namespace SSDTO {
class Disconnect_DTO;
struct Disconnect_DTODefaultTypeInternal;
extern Disconnect_DTODefaultTypeInternal _Disconnect_DTO_default_instance_;
}  // namespace SSDTO
PROTOBUF_NAMESPACE_OPEN
template<> ::SSDTO::Disconnect_DTO* Arena::CreateMaybeMessage<::SSDTO::Disconnect_DTO>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace SSDTO {

// ===================================================================

class Disconnect_DTO final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SSDTO.Disconnect_DTO) */ {
 public:
  inline Disconnect_DTO() : Disconnect_DTO(nullptr) {}
  ~Disconnect_DTO() override;
  explicit PROTOBUF_CONSTEXPR Disconnect_DTO(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Disconnect_DTO(const Disconnect_DTO& from);
  Disconnect_DTO(Disconnect_DTO&& from) noexcept
    : Disconnect_DTO() {
    *this = ::std::move(from);
  }

  inline Disconnect_DTO& operator=(const Disconnect_DTO& from) {
    CopyFrom(from);
    return *this;
  }
  inline Disconnect_DTO& operator=(Disconnect_DTO&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Disconnect_DTO& default_instance() {
    return *internal_default_instance();
  }
  static inline const Disconnect_DTO* internal_default_instance() {
    return reinterpret_cast<const Disconnect_DTO*>(
               &_Disconnect_DTO_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Disconnect_DTO& a, Disconnect_DTO& b) {
    a.Swap(&b);
  }
  inline void Swap(Disconnect_DTO* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Disconnect_DTO* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Disconnect_DTO* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Disconnect_DTO>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Disconnect_DTO& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Disconnect_DTO& from) {
    Disconnect_DTO::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Disconnect_DTO* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SSDTO.Disconnect_DTO";
  }
  protected:
  explicit Disconnect_DTO(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSsidFieldNumber = 1,
    kIpFieldNumber = 2,
    kTypeFieldNumber = 3,
  };
  // bytes ssid = 1;
  void clear_ssid();
  const std::string& ssid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ssid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ssid();
  PROTOBUF_NODISCARD std::string* release_ssid();
  void set_allocated_ssid(std::string* ssid);
  private:
  const std::string& _internal_ssid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ssid(const std::string& value);
  std::string* _internal_mutable_ssid();
  public:

  // bytes ip = 2;
  void clear_ip();
  const std::string& ip() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ip(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ip();
  PROTOBUF_NODISCARD std::string* release_ip();
  void set_allocated_ip(std::string* ip);
  private:
  const std::string& _internal_ip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ip(const std::string& value);
  std::string* _internal_mutable_ip();
  public:

  // .SSDTO.Business_Type type = 3;
  void clear_type();
  ::SSDTO::Business_Type type() const;
  void set_type(::SSDTO::Business_Type value);
  private:
  ::SSDTO::Business_Type _internal_type() const;
  void _internal_set_type(::SSDTO::Business_Type value);
  public:

  // @@protoc_insertion_point(class_scope:SSDTO.Disconnect_DTO)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ssid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ip_;
    int type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_DisconnectDTO_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Disconnect_DTO

// bytes ssid = 1;
inline void Disconnect_DTO::clear_ssid() {
  _impl_.ssid_.ClearToEmpty();
}
inline const std::string& Disconnect_DTO::ssid() const {
  // @@protoc_insertion_point(field_get:SSDTO.Disconnect_DTO.ssid)
  return _internal_ssid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Disconnect_DTO::set_ssid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.ssid_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SSDTO.Disconnect_DTO.ssid)
}
inline std::string* Disconnect_DTO::mutable_ssid() {
  std::string* _s = _internal_mutable_ssid();
  // @@protoc_insertion_point(field_mutable:SSDTO.Disconnect_DTO.ssid)
  return _s;
}
inline const std::string& Disconnect_DTO::_internal_ssid() const {
  return _impl_.ssid_.Get();
}
inline void Disconnect_DTO::_internal_set_ssid(const std::string& value) {
  
  _impl_.ssid_.Set(value, GetArenaForAllocation());
}
inline std::string* Disconnect_DTO::_internal_mutable_ssid() {
  
  return _impl_.ssid_.Mutable(GetArenaForAllocation());
}
inline std::string* Disconnect_DTO::release_ssid() {
  // @@protoc_insertion_point(field_release:SSDTO.Disconnect_DTO.ssid)
  return _impl_.ssid_.Release();
}
inline void Disconnect_DTO::set_allocated_ssid(std::string* ssid) {
  if (ssid != nullptr) {
    
  } else {
    
  }
  _impl_.ssid_.SetAllocated(ssid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ssid_.IsDefault()) {
    _impl_.ssid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SSDTO.Disconnect_DTO.ssid)
}

// bytes ip = 2;
inline void Disconnect_DTO::clear_ip() {
  _impl_.ip_.ClearToEmpty();
}
inline const std::string& Disconnect_DTO::ip() const {
  // @@protoc_insertion_point(field_get:SSDTO.Disconnect_DTO.ip)
  return _internal_ip();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Disconnect_DTO::set_ip(ArgT0&& arg0, ArgT... args) {
 
 _impl_.ip_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SSDTO.Disconnect_DTO.ip)
}
inline std::string* Disconnect_DTO::mutable_ip() {
  std::string* _s = _internal_mutable_ip();
  // @@protoc_insertion_point(field_mutable:SSDTO.Disconnect_DTO.ip)
  return _s;
}
inline const std::string& Disconnect_DTO::_internal_ip() const {
  return _impl_.ip_.Get();
}
inline void Disconnect_DTO::_internal_set_ip(const std::string& value) {
  
  _impl_.ip_.Set(value, GetArenaForAllocation());
}
inline std::string* Disconnect_DTO::_internal_mutable_ip() {
  
  return _impl_.ip_.Mutable(GetArenaForAllocation());
}
inline std::string* Disconnect_DTO::release_ip() {
  // @@protoc_insertion_point(field_release:SSDTO.Disconnect_DTO.ip)
  return _impl_.ip_.Release();
}
inline void Disconnect_DTO::set_allocated_ip(std::string* ip) {
  if (ip != nullptr) {
    
  } else {
    
  }
  _impl_.ip_.SetAllocated(ip, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ip_.IsDefault()) {
    _impl_.ip_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SSDTO.Disconnect_DTO.ip)
}

// .SSDTO.Business_Type type = 3;
inline void Disconnect_DTO::clear_type() {
  _impl_.type_ = 0;
}
inline ::SSDTO::Business_Type Disconnect_DTO::_internal_type() const {
  return static_cast< ::SSDTO::Business_Type >(_impl_.type_);
}
inline ::SSDTO::Business_Type Disconnect_DTO::type() const {
  // @@protoc_insertion_point(field_get:SSDTO.Disconnect_DTO.type)
  return _internal_type();
}
inline void Disconnect_DTO::_internal_set_type(::SSDTO::Business_Type value) {
  
  _impl_.type_ = value;
}
inline void Disconnect_DTO::set_type(::SSDTO::Business_Type value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:SSDTO.Disconnect_DTO.type)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace SSDTO

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_DisconnectDTO_2eproto
