// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: FileTransferDTO.proto

#include "FileTransferDTO.pb.h"
#include "FileTransferDTO.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* FileTransferService_method_names[] = {
  "/FileTransferService/InitUpload",
  "/FileTransferService/UploadFile",
  "/FileTransferService/DownloadFile",
};

std::unique_ptr< FileTransferService::Stub> FileTransferService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FileTransferService::Stub> stub(new FileTransferService::Stub(channel, options));
  return stub;
}

FileTransferService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_InitUpload_(FileTransferService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UploadFile_(FileTransferService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  , rpcmethod_DownloadFile_(FileTransferService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status FileTransferService::Stub::InitUpload(::grpc::ClientContext* context, const ::FileInitRequest& request, ::FileInitResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::FileInitRequest, ::FileInitResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_InitUpload_, context, request, response);
}

void FileTransferService::Stub::async::InitUpload(::grpc::ClientContext* context, const ::FileInitRequest* request, ::FileInitResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::FileInitRequest, ::FileInitResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_InitUpload_, context, request, response, std::move(f));
}

void FileTransferService::Stub::async::InitUpload(::grpc::ClientContext* context, const ::FileInitRequest* request, ::FileInitResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_InitUpload_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::FileInitResponse>* FileTransferService::Stub::PrepareAsyncInitUploadRaw(::grpc::ClientContext* context, const ::FileInitRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::FileInitResponse, ::FileInitRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_InitUpload_, context, request);
}

::grpc::ClientAsyncResponseReader< ::FileInitResponse>* FileTransferService::Stub::AsyncInitUploadRaw(::grpc::ClientContext* context, const ::FileInitRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncInitUploadRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientWriter< ::FileChunk>* FileTransferService::Stub::UploadFileRaw(::grpc::ClientContext* context, ::FileResponse* response) {
  return ::grpc::internal::ClientWriterFactory< ::FileChunk>::Create(channel_.get(), rpcmethod_UploadFile_, context, response);
}

void FileTransferService::Stub::async::UploadFile(::grpc::ClientContext* context, ::FileResponse* response, ::grpc::ClientWriteReactor< ::FileChunk>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::FileChunk>::Create(stub_->channel_.get(), stub_->rpcmethod_UploadFile_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::FileChunk>* FileTransferService::Stub::AsyncUploadFileRaw(::grpc::ClientContext* context, ::FileResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::FileChunk>::Create(channel_.get(), cq, rpcmethod_UploadFile_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::FileChunk>* FileTransferService::Stub::PrepareAsyncUploadFileRaw(::grpc::ClientContext* context, ::FileResponse* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::FileChunk>::Create(channel_.get(), cq, rpcmethod_UploadFile_, context, response, false, nullptr);
}

::grpc::ClientReader< ::FileChunk>* FileTransferService::Stub::DownloadFileRaw(::grpc::ClientContext* context, const ::FileRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::FileChunk>::Create(channel_.get(), rpcmethod_DownloadFile_, context, request);
}

void FileTransferService::Stub::async::DownloadFile(::grpc::ClientContext* context, const ::FileRequest* request, ::grpc::ClientReadReactor< ::FileChunk>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::FileChunk>::Create(stub_->channel_.get(), stub_->rpcmethod_DownloadFile_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::FileChunk>* FileTransferService::Stub::AsyncDownloadFileRaw(::grpc::ClientContext* context, const ::FileRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::FileChunk>::Create(channel_.get(), cq, rpcmethod_DownloadFile_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::FileChunk>* FileTransferService::Stub::PrepareAsyncDownloadFileRaw(::grpc::ClientContext* context, const ::FileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::FileChunk>::Create(channel_.get(), cq, rpcmethod_DownloadFile_, context, request, false, nullptr);
}

FileTransferService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileTransferService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileTransferService::Service, ::FileInitRequest, ::FileInitResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileTransferService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::FileInitRequest* req,
             ::FileInitResponse* resp) {
               return service->InitUpload(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileTransferService_method_names[1],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< FileTransferService::Service, ::FileChunk, ::FileResponse>(
          [](FileTransferService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::FileChunk>* reader,
             ::FileResponse* resp) {
               return service->UploadFile(ctx, reader, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileTransferService_method_names[2],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< FileTransferService::Service, ::FileRequest, ::FileChunk>(
          [](FileTransferService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::FileRequest* req,
             ::grpc::ServerWriter<::FileChunk>* writer) {
               return service->DownloadFile(ctx, req, writer);
             }, this)));
}

FileTransferService::Service::~Service() {
}

::grpc::Status FileTransferService::Service::InitUpload(::grpc::ServerContext* context, const ::FileInitRequest* request, ::FileInitResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileTransferService::Service::UploadFile(::grpc::ServerContext* context, ::grpc::ServerReader< ::FileChunk>* reader, ::FileResponse* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileTransferService::Service::DownloadFile(::grpc::ServerContext* context, const ::FileRequest* request, ::grpc::ServerWriter< ::FileChunk>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


