// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: HeartbeatDTO.proto

#include "HeartbeatDTO.pb.h"
#include "HeartbeatDTO.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* MediaService_method_names[] = {
  "/MediaService/HeartbeatHandler",
};

std::unique_ptr< MediaService::Stub> MediaService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MediaService::Stub> stub(new MediaService::Stub(channel, options));
  return stub;
}

MediaService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_HeartbeatHandler_(MediaService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MediaService::Stub::HeartbeatHandler(::grpc::ClientContext* context, const ::HeartbeatRequest& request, ::HeartbeatResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::HeartbeatRequest, ::HeartbeatResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_HeartbeatHandler_, context, request, response);
}

void MediaService::Stub::async::HeartbeatHandler(::grpc::ClientContext* context, const ::HeartbeatRequest* request, ::HeartbeatResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::HeartbeatRequest, ::HeartbeatResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HeartbeatHandler_, context, request, response, std::move(f));
}

void MediaService::Stub::async::HeartbeatHandler(::grpc::ClientContext* context, const ::HeartbeatRequest* request, ::HeartbeatResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HeartbeatHandler_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::HeartbeatResponse>* MediaService::Stub::PrepareAsyncHeartbeatHandlerRaw(::grpc::ClientContext* context, const ::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::HeartbeatResponse, ::HeartbeatRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_HeartbeatHandler_, context, request);
}

::grpc::ClientAsyncResponseReader< ::HeartbeatResponse>* MediaService::Stub::AsyncHeartbeatHandlerRaw(::grpc::ClientContext* context, const ::HeartbeatRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHeartbeatHandlerRaw(context, request, cq);
  result->StartCall();
  return result;
}

MediaService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MediaService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MediaService::Service, ::HeartbeatRequest, ::HeartbeatResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MediaService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::HeartbeatRequest* req,
             ::HeartbeatResponse* resp) {
               return service->HeartbeatHandler(ctx, req, resp);
             }, this)));
}

MediaService::Service::~Service() {
}

::grpc::Status MediaService::Service::HeartbeatHandler(::grpc::ServerContext* context, const ::HeartbeatRequest* request, ::HeartbeatResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


