// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DTO.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_DTO_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_DTO_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_DTO_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_DTO_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_DTO_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace SSDTO {

enum Business_Type : int {
  LOGIN = 0,
  ENROLL = 1,
  FOWARD_MSG = 2,
  DISCONNECT = 3,
  GET_CONTACTLIST = 4,
  ADD_FRIEND = 5,
  GET_EMAILCODE = 6,
  FRIEND_SEARCH = 7,
  FILE_TRANSFER_REQUEST = 8,
  FILE_CHUNK = 9,
  MISSING_CHUNK_REQUEST = 10,
  Business_Type_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Business_Type_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Business_Type_IsValid(int value);
constexpr Business_Type Business_Type_MIN = LOGIN;
constexpr Business_Type Business_Type_MAX = MISSING_CHUNK_REQUEST;
constexpr int Business_Type_ARRAYSIZE = Business_Type_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Business_Type_descriptor();
template<typename T>
inline const std::string& Business_Type_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Business_Type>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Business_Type_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Business_Type_descriptor(), enum_t_value);
}
inline bool Business_Type_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Business_Type* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Business_Type>(
    Business_Type_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace SSDTO

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::SSDTO::Business_Type> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::SSDTO::Business_Type>() {
  return ::SSDTO::Business_Type_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_DTO_2eproto
