// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: WebRTCSignaling.proto

#include "WebRTCSignaling.pb.h"
#include "WebRTCSignaling.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* WebRTCSignalingService_method_names[] = {
  "/WebRTCSignalingService/CreateOffer",
  "/WebRTCSignalingService/HandleAnswer",
  "/WebRTCSignalingService/ExchangeIceCandidate",
  "/WebRTCSignalingService/SignalingStream",
};

std::unique_ptr< WebRTCSignalingService::Stub> WebRTCSignalingService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< WebRTCSignalingService::Stub> stub(new WebRTCSignalingService::Stub(channel, options));
  return stub;
}

WebRTCSignalingService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CreateOffer_(WebRTCSignalingService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_HandleAnswer_(WebRTCSignalingService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ExchangeIceCandidate_(WebRTCSignalingService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SignalingStream_(WebRTCSignalingService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::Status WebRTCSignalingService::Stub::CreateOffer(::grpc::ClientContext* context, const ::SignalingRequest& request, ::SignalingResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::SignalingRequest, ::SignalingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateOffer_, context, request, response);
}

void WebRTCSignalingService::Stub::async::CreateOffer(::grpc::ClientContext* context, const ::SignalingRequest* request, ::SignalingResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::SignalingRequest, ::SignalingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateOffer_, context, request, response, std::move(f));
}

void WebRTCSignalingService::Stub::async::CreateOffer(::grpc::ClientContext* context, const ::SignalingRequest* request, ::SignalingResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateOffer_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::SignalingResponse>* WebRTCSignalingService::Stub::PrepareAsyncCreateOfferRaw(::grpc::ClientContext* context, const ::SignalingRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::SignalingResponse, ::SignalingRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateOffer_, context, request);
}

::grpc::ClientAsyncResponseReader< ::SignalingResponse>* WebRTCSignalingService::Stub::AsyncCreateOfferRaw(::grpc::ClientContext* context, const ::SignalingRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateOfferRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status WebRTCSignalingService::Stub::HandleAnswer(::grpc::ClientContext* context, const ::SignalingRequest& request, ::SignalingResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::SignalingRequest, ::SignalingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_HandleAnswer_, context, request, response);
}

void WebRTCSignalingService::Stub::async::HandleAnswer(::grpc::ClientContext* context, const ::SignalingRequest* request, ::SignalingResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::SignalingRequest, ::SignalingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HandleAnswer_, context, request, response, std::move(f));
}

void WebRTCSignalingService::Stub::async::HandleAnswer(::grpc::ClientContext* context, const ::SignalingRequest* request, ::SignalingResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HandleAnswer_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::SignalingResponse>* WebRTCSignalingService::Stub::PrepareAsyncHandleAnswerRaw(::grpc::ClientContext* context, const ::SignalingRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::SignalingResponse, ::SignalingRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_HandleAnswer_, context, request);
}

::grpc::ClientAsyncResponseReader< ::SignalingResponse>* WebRTCSignalingService::Stub::AsyncHandleAnswerRaw(::grpc::ClientContext* context, const ::SignalingRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHandleAnswerRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status WebRTCSignalingService::Stub::ExchangeIceCandidate(::grpc::ClientContext* context, const ::IceCandidateRequest& request, ::SignalingResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::IceCandidateRequest, ::SignalingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ExchangeIceCandidate_, context, request, response);
}

void WebRTCSignalingService::Stub::async::ExchangeIceCandidate(::grpc::ClientContext* context, const ::IceCandidateRequest* request, ::SignalingResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::IceCandidateRequest, ::SignalingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExchangeIceCandidate_, context, request, response, std::move(f));
}

void WebRTCSignalingService::Stub::async::ExchangeIceCandidate(::grpc::ClientContext* context, const ::IceCandidateRequest* request, ::SignalingResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExchangeIceCandidate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::SignalingResponse>* WebRTCSignalingService::Stub::PrepareAsyncExchangeIceCandidateRaw(::grpc::ClientContext* context, const ::IceCandidateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::SignalingResponse, ::IceCandidateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ExchangeIceCandidate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::SignalingResponse>* WebRTCSignalingService::Stub::AsyncExchangeIceCandidateRaw(::grpc::ClientContext* context, const ::IceCandidateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncExchangeIceCandidateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReaderWriter< ::SignalingMessage, ::SignalingMessage>* WebRTCSignalingService::Stub::SignalingStreamRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::SignalingMessage, ::SignalingMessage>::Create(channel_.get(), rpcmethod_SignalingStream_, context);
}

void WebRTCSignalingService::Stub::async::SignalingStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::SignalingMessage,::SignalingMessage>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::SignalingMessage,::SignalingMessage>::Create(stub_->channel_.get(), stub_->rpcmethod_SignalingStream_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::SignalingMessage, ::SignalingMessage>* WebRTCSignalingService::Stub::AsyncSignalingStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::SignalingMessage, ::SignalingMessage>::Create(channel_.get(), cq, rpcmethod_SignalingStream_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::SignalingMessage, ::SignalingMessage>* WebRTCSignalingService::Stub::PrepareAsyncSignalingStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::SignalingMessage, ::SignalingMessage>::Create(channel_.get(), cq, rpcmethod_SignalingStream_, context, false, nullptr);
}

WebRTCSignalingService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WebRTCSignalingService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WebRTCSignalingService::Service, ::SignalingRequest, ::SignalingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WebRTCSignalingService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::SignalingRequest* req,
             ::SignalingResponse* resp) {
               return service->CreateOffer(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WebRTCSignalingService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WebRTCSignalingService::Service, ::SignalingRequest, ::SignalingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WebRTCSignalingService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::SignalingRequest* req,
             ::SignalingResponse* resp) {
               return service->HandleAnswer(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WebRTCSignalingService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WebRTCSignalingService::Service, ::IceCandidateRequest, ::SignalingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WebRTCSignalingService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::IceCandidateRequest* req,
             ::SignalingResponse* resp) {
               return service->ExchangeIceCandidate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WebRTCSignalingService_method_names[3],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< WebRTCSignalingService::Service, ::SignalingMessage, ::SignalingMessage>(
          [](WebRTCSignalingService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::SignalingMessage,
             ::SignalingMessage>* stream) {
               return service->SignalingStream(ctx, stream);
             }, this)));
}

WebRTCSignalingService::Service::~Service() {
}

::grpc::Status WebRTCSignalingService::Service::CreateOffer(::grpc::ServerContext* context, const ::SignalingRequest* request, ::SignalingResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status WebRTCSignalingService::Service::HandleAnswer(::grpc::ServerContext* context, const ::SignalingRequest* request, ::SignalingResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status WebRTCSignalingService::Service::ExchangeIceCandidate(::grpc::ServerContext* context, const ::IceCandidateRequest* request, ::SignalingResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status WebRTCSignalingService::Service::SignalingStream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::SignalingMessage, ::SignalingMessage>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


